services:
  db:
    image: postgres:18
    container_name: agendamentos-db
    environment:
      POSTGRES_DB: agendamentos
      POSTGRES_USER: agendamentos
      POSTGRES_PASSWORD: agendamentos
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: