spring.config.import=optional:file:.env[.properties]
spring.application.name=agendamentos

# --- Conexão ---
spring.datasource.url=jdbc:postgresql://localhost:5433/agendamentos
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# --- Flyway é o dono do schema ---
spring.flyway.enabled=true

# --- JPA/Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true